# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
# Generate a sequence of 15 floats between a specified range
#np.linspace(start, stop, num)
float_sequence = np.linspace(0, 15, num=15)
float_sequence

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
array_3d = np.array([1.1, 2.1, 3.1,4.1, 5.1, 6.1,7.1, 8.1, 9.1,10.1, 11.1, 12.1]).reshape(2,2,3)
array_3d

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [5]:
# Printing all properties of the array in one line using f-strings
print(f"Array's type: {type(array_3d)}\nArray's elements datatype: {array_3d.dtype}\n"
      f"Array's shape: {array_3d.shape}\nArray's size: {array_3d.size}\n"
      f"Array's dimension: {array_3d.ndim}")

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [6]:
#changed the dimention using reshape
array_4d = array_3d.reshape(2, 1, 2, 3)

#printed the new array and the dimention and shape
print(f"New Array \n{array_4d}\nNew array's dimension: {new_array_4d.ndim}\n New array's shape: {new_array_4d.shape}")

NameError: name 'new_array_4d' is not defined

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [ ]:
#used astype to change the values type to integer
array_int = array_4d.astype(int)

# Printing the new array with integer values
print(f"New array with integer values:\n{array_int}")

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [ ]:
print("All elements in the int array:")
# Printing all array's elements using a for loop with nditer
for element in np.nditer(array_int):
    print(element)

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [ ]:
print(f"Number 8: {array_int[1, 0, 0, 1]}")  # Accessing number 8 at index [1, 0, 0, 1]

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [ ]:
print(f"Number 5: {array_int[0, 0, 1, 1]}")# Accessing number 5 at index [0, 1, 1, 1]
print(f"Number 6: {array_int[0, 0, 1, 2]}")# Accessing number 6 at index [0, 1, 1, 2]

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [ ]:
# Using np.where() to find the index of the number 8
# Printing the index
print(f"Index of number 8: {np.where(array_int == 8)}")

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [41]:
array_int = array_int.reshape(2, 3, 2)

# Printing the reshaped array
print(f"Reshaped Array:\n{array_int}")

Reshaped Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [13]:
# Defining the arrays
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

# Joining the arrays without specifying the axis
joined_array = np.concatenate((arr1, arr2))

# the result
print(f"Joined Array (without specifying axis):{joined_array}")

Joined Array (without specifying axis):[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [11]:
# Joining the arrays along rows (axis=1)
joined_array_a1 = np.concatenate((arr1, arr2), axis=1)

#the result
print(f"Joined Array (along rows with axis=1):\n{joined_array_a1}")

Joined Array (along rows with axis=1):
[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [17]:

split_arr = np.split(joined_array, 2, axis=1)

print(f"i split the array into two array: \n{split_arr}")


i split the array into two array: 
[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
